# GET all tasks
GET https://flask-api-youssuf-ctdxg4bbapepgrhb.canadacentral-01.azurewebsites.net/tasks
Accept: application/json


####
# GET a single task
GET https://flask-api-youssuf-ctdxg4bbapepgrhb.canadacentral-01.azurewebsites.net/tasks/1
Accept: application/json

###

# GET a task that doesnt exist 
GET https://flask-api-youssuf-ctdxg4bbapepgrhb.canadacentral-01.azurewebsites.net/tasks/100
Accept: application/json

###

# POST create a new task
POST https://flask-api-youssuf-ctdxg4bbapepgrhb.canadacentral-01.azurewebsites.net/tasks
Content-Type: application/json

{
  "title": "Test",
  "user_id": 1
}

###

# POST a task with no title
POST https://flask-api-youssuf-ctdxg4bbapepgrhb.canadacentral-01.azurewebsites.net/tasks
Content-Type: application/json

{
  "user_id": 1
}

###


# POST a task with invalid user_id
POST https://flask-api-youssuf-ctdxg4bbapepgrhb.canadacentral-01.azurewebsites.net/tasks
Content-Type: application/json

{
  "title": "Test",
  "user_id": 100
}

###




# PUT update a task by ID
PUT https://flask-api-youssuf-ctdxg4bbapepgrhb.canadacentral-01.azurewebsites.net/tasks/1
Content-Type: application/json

{
  "completed": true
}

###

# DELETE a task by ID
DELETE https://flask-api-youssuf-ctdxg4bbapepgrhb.canadacentral-01.azurewebsites.net/tasks/1


###
GET https://flask-api-youssuf-ctdxg4bbapepgrhb.canadacentral-01.azurewebsites.net/users/1/tasks
Accept: application/json

###